name: base
channels:
- conda-forge/label/vtk_dev
- conda-forge
dependencies:
- python >=3.7
- pip
- mesalib
- ffmpeg
- vtk
- traits
- scipy
- numpy
- matplotlib-base
- pyvista >=0.30
- nilearn
- nibabel
- nbformat
- nbclient
- jupyter
- ipympl
- ipywidgets
- ipyvtklink
- jupyter_client !=6.1.5
- mffpy>=0.5.7
- pip:
  - mne
